name: Build Android

on:
  push:
    branches:
      - main
      - master
      - '*Test*'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      project: PopTemplate
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build Android lib
      uses: NewChromantics/PopAction_BuildAndroid@v2
      with:
        buildtargetname: "PopTemplate"
        buildpath: "PopTemplate.Android/libPopTemplate"
        
    #- name: Build Android test app
    #  uses: NewChromantics/PopAction_BuildAndroid@v2
    #  with:
    #    buildtargetname: "PopH264"
    #    buildpath: "PopH264.Android/PopH264TestApp"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        # tsdk: these env vars are set in each of the actions
        name: ${{ env.UPLOAD_NAME }}
        path: ${{ env.UPLOAD_DIR }}
